spring.application.name=sistema
# ============================
# CONFIGURAÇÃO DO POSTGRESQL
# ============================
spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=postgres
spring.datasource.password=123

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================
# JPA / HIBERNATE
# ============================

# cria/atualiza tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
# opções: none | validate | update | create | create-drop

# mostra as queries no console
spring.jpa.show-sql=true

# formata as queries
spring.jpa.properties.hibernate.format_sql=true

# Dialeto PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
