spring.application.name=sistema
spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=postgres
spring.datasource.password=123

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto do PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Página de login padrão
spring.security.user.name=admin
spring.security.user.password=admin
